spring:
#  liquibase:
#    change-log: "classpath:/db/changelog/db.changelog-persistence.xml"
#    enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    # Strongly recommend to set this property to "none"
    # production environment!
    hibernate.ddl-auto: create-drop
  datasource:
    ## You often do not need to specify the driver-class-name,
    ## since Spring Boot can deduce it for most databases from the url.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/books?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
    username: root
    password: backbase
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# One of logging libraries (slf4j, jul, common, sysout)
decorator:
  datasource:
    datasource-proxy:
      query:
        enable-logging: true
        log-level: info
      slow-query:
        enable-logging: true
        log-level: info
        threshold: 1

## Logger name to log all queries, default depends on chosen logging, e.g. net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener
#decorator.datasource.datasource-proxy.query.logger-name=
#
#decorator.datasource.datasource-proxy.slow-query.enable-logging=true
#decorator.datasource.datasource-proxy.slow-query.log-level=warn
#decorator.datasource.datasource-proxy.slow-query.logger-name=
## Number of seconds to consider query as slow and log it
#decorator.datasource.datasource-proxy.slow-query.threshold=300
#
#decorator.datasource.datasource-proxy.multiline=true
#decorator.datasource.datasource-proxy.json-format=false
#  # Enable Query Metrics
#decorator.datasource.datasource-proxy.count-query=false

